apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-helm
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https:/kubernetes.default.svc
  project: default
  source:
    helm:
      valueFiles:
        - values.yaml
    repoURL: https://github.com/dkudlek/nd064_course_1.git/exercises/helm
    targetRevision: HEAD
